//
//  PhotoDetailViewController.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 16/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailDisplayLogic: class {
    func displayInitialData(viewModel: PhotoDetailScene.Load.ViewModel)
}

class PhotoDetailViewController: UIViewController, PhotoDetailDisplayLogic {
    var interactor: PhotoDetailBusinessLogic?
    var router: (NSObjectProtocol & PhotoDetailRoutingLogic & PhotoDetailDataPassing)?
    
    let photoDetailView = PhotoDetailView()
    var photo = Photo()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = PhotoDetailInteractor()
        let presenter = PhotoDetailPresenter()
        let router = PhotoDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    override func loadView() {
        view = photoDetailView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Photo Detail"
        
        loadInitialData()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func loadInitialData() {
        let request = PhotoDetailScene.Load.Request()
        interactor?.doInitialData(request: request)
    }
    
    func displayInitialData(viewModel: PhotoDetailScene.Load.ViewModel) {
        photoDetailView.camaraNameLabel.text = viewModel.photo.camera?.cameraName
        photoDetailView.photo.getImage(urlImage: viewModel.photo.urlPhoto)
    }
}
