//
//  PhotoDetailInteractor.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 16/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailBusinessLogic {
    func doInitialData(request: PhotoDetailScene.Load.Request)
}

protocol PhotoDetailDataStore {
    var photo: Photo? { get set }
}

class PhotoDetailInteractor: PhotoDetailBusinessLogic, PhotoDetailDataStore {
    var presenter: PhotoDetailPresentationLogic?
    var worker: PhotoDetailWorker?
    var photo: Photo?
    
    // MARK: Do something
    
    func doInitialData(request: PhotoDetailScene.Load.Request) {
        let response = PhotoDetailScene.Load.Response(photo: photo!)
        self.presenter?.presentInitialData(response: response)
    }
}
