//
//  PhotoDetailPresenter.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 16/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailPresentationLogic {
    func presentInitialData(response: PhotoDetailScene.Load.Response)
}

class PhotoDetailPresenter: PhotoDetailPresentationLogic {
    weak var viewController: PhotoDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentInitialData(response: PhotoDetailScene.Load.Response) {
        let viewModel = PhotoDetailScene.Load.ViewModel(photo: response.photo)
        viewController?.displayInitialData(viewModel: viewModel)
    }
}
