//
//  PhotoPresenter.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 04/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoPresentationLogic {
    func presentInitialData(response: PhotoScene.Load.Response)
}

class PhotoPresenter: PhotoPresentationLogic {
    weak var viewController: PhotoDisplayLogic?
    
    // MARK: Do something
    
    func presentInitialData(response: PhotoScene.Load.Response) {
        let viewModel = PhotoScene.Load.ViewModel(photos: response.photos)
        viewController?.displayInitialData(viewModel: viewModel)
    }
}
