//
//  PhotoWorker.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 04/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhotoWorker {
    
    func fetchPhotos(camera: String, date: String, completionHandler: @escaping ([Photo]) -> Void) {
        NetworkManager.shared.getPhotos(withCameraAndDate: camera, date: date) { photos in
            completionHandler(photos)
        }
    }
    
    
}
