//
//  PhotoInteractor.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 04/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoBusinessLogic {
    func doLoadInitialData(request: PhotoScene.Load.Request)
}

protocol PhotoDataStore {
    var camera: String { get set }
    var date: String { get set }
}

class PhotoInteractor: PhotoBusinessLogic, PhotoDataStore {
    var presenter: PhotoPresentationLogic?
    var worker: PhotoWorker?
    var camera: String = ""
    var date: String = ""
    
    // MARK: Do something
    
    func doLoadInitialData(request: PhotoScene.Load.Request) {
        worker = PhotoWorker()
        worker?.fetchPhotos(camera: camera, date: date, completionHandler: { photos in
            let response = PhotoScene.Load.Response(photos: photos)
            self.presenter?.presentInitialData(response: response)
        })
    }
}
