//
//  PhotoModels.swift
//  BeBlue
//
//  Created by Marcio Habigzang Brufatto on 04/07/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotoScene {
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        struct Response {
            let photos: [Photo]
        }
        struct ViewModel {
            let photos: [Photo]
        }
    }
    
    enum loadImage {
        struct Request {
            let photo: Photo
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
